# SPDX-License-Identifier: GPL-2.0

obj-y += core/

obj-$(CONFIG_CUSTOM_KERNEL_SENSORHUB) += mtk_nanohub/
obj-$(CONFIG_MTK_SENSORHUB) += sensorhub/
obj-$(CONFIG_MTK_HF_LSM6DSM_SECONDARY) += lsm6dsm_secondary/
obj-$(CONFIG_MTK_HF_TEST_CASE) += test/
obj-$(CONFIG_OPLUS_FEATURE_SENSOR_DEVINFO_V2) += oplus_sensor_devinfo/
obj-$(CONFIG_OPLUS_SENSOR_FB_MTK) += oplus_sensor_feedback/
obj-y += oplus_consumer_ir/
