# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_POWER_RESET)	+= reset/
obj-$(CONFIG_POWER_SUPPLY)	+= supply/
obj-$(CONFIG_OPLUS_CHARGER)	+= oplus/

obj-$(CONFIG_OPLUS_CHG_V2)	:= oplus_chg_symbol.o
